feat: allow add custom atdatabase options
mateonunez/fastify-at-postgres pull request #31
Opened 2023-11-09 11:17 UTC by leandroandrade

Hi, the proposal of this PR is to allow users to use custom `atdatabase` configurations.

Message warning like this `bigIntMode currently defaults to "number" but will default to "bigint" in the next major version of @databases/pg. Set it explicitly to disable this warning.` can solved pass `bigIntMode: 'string'` to atdatabase lib.

2023-11-09 11:26 UTC, mateonunez commented
Hey @leandroandrade, thank you so much for your contribution! I appreciate it very much.

Don't worry about the CI, I'm working in a branch to improve this package as I did in https://github.com/mateonunez/fastify-at-mysql. The changes make the package more stable and improve the type system and also the tests.

I will review this PR as soon as possible and merge it to `main` so I can ultimate the changes and ship this amazing improvement!

2023-11-09 21:51 UTC, mateonunez requested changes
The changes are great! I left just a small comment for a test.

Can you please rebase this PR with `main`? So we can ship it into the new `v0.3` release!

2023-11-09 21:51 UTC, mateonunez commented on test/fastify-postgres.test.js
> +    connectionString: 'postgres://postgres:postgres@localhost:5432/test',
Please, replace `localhost` with `127.0.0.1`

2023-11-09 22:43 UTC, leandroandrade commented on test/fastify-postgres.test.js
> +    connectionString: 'postgres://postgres:postgres@localhost:5432/test',
I put it in the code in the same way it already exists, using `localhost`, for example, line 48, 97, Just to maintain the same code.

2023-11-09 22:59 UTC, leandroandrade commented on test/fastify-postgres.test.js
> +    connectionString: 'postgres://postgres:postgres@localhost:5432/test',
To attend your request, I need to update the regex that validate connectionString.

2023-11-10 07:19 UTC, mateonunez approved these changes
LGTM! 🚀

2023-11-10 07:19 UTC, merged